### ISSUE TITLE
Is LocalFilters.jl needed?

### ISSUE THREAD

**Issue by alex-s-gardner** [Deltares/Geomorphometry.jl#34]
Is there a reason to use `LocalFilters.jl` over `ImageFiltering.jl` with `mapwindow` ? Maybe there is a good reason that I'm not aware of.

**Comment by rafaqz** [comment]
Or Stencils.jl should be 10x faster than either of those for smaller windows ;)

**Comment by evetion** [comment]
Yeah, the default mapwindow of ImageFiltering *can* be very slow. Localfilters is much faster, especially in certain optimizable cases (erosion etc). I hope to eventually migrate to Stencils, but it probably misses some optimizations like [separable filters](https://emmt.github.io/LocalFilters.jl/dev/separable/) (rafaqz, please correct me if I'm wrong).

**Comment by alex-s-gardner** [comment]
Thanks both.. I was just curious as I saw both `ImageFiltering` and `LocalFilters` in the .toml

**Comment by evetion** [comment]
Good point, I can probably remove ImageFiltering rather easily.
